export const OpenAiModels = [
  {
    name: "Q & A",
    id: "q&a",
    desc: "Answer questions based on existing knowledge.",
    color: "#F24E70",
    img: "https://cdn.pixabay.com/photo/2012/04/10/23/44/question-27106_1280.png",
    opt: {
      model: "text-davinci-003",
      prompt:
        'I am a highly intelligent question answering bot. If you ask me a question that is rooted in truth, I will give you the answer. If you ask me a question that is nonsense, trickery, or has no clear answer, I will respond with "Unknown".\n\nQ: What is human life expectancy in the United States?\nA: Human life expectancy in the United States is 78 years.\n\nQ: Who was president of the United States in 1955?\nA: Dwight D. Eisenhower was president of the United States in 1955.\n\nQ: Which party did he belong to?\nA: He belonged to the Republican Party.\n\nQ: What is the square root of banana?\nA: Unknown\n\nQ: How does a telescope work?\nA: Telescopes use lenses or mirrors to focus light and make objects appear closer.\n\nQ: Where were the 1992 Olympics held?\nA: The 1992 Olympics were held in Barcelona, Spain.\n\nQ: How many squigs are in a bonk?\nA: Unknown\n\nQ: Where is the Valley of Kings?\nA:',
      temperature: 0,
      max_tokens: 100,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stop: ["\n"],
    },
  },
  {
    name: "Grammar correction",
    id: "grammar",
    desc: "Corrects sentences into standard English.",
    color: "#B4F8C8",
    img: "https://cdn-icons-png.flaticon.com/512/73/73921.png",
    opt: {
      model: "text-davinci-003",
      prompt: "Correct this to standard English:\n\nShe no went to the market.",
      temperature: 0,
      max_tokens: 60,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Summarize for a 2nd grader",
    id: "Summarize",
    desc: "Translates difficult text into simpler concepts.",
    color: "#DE0001",
    img: "https://cdn-icons-png.flaticon.com/512/74/74540.png",
    opt: {
      model: "text-davinci-003",
      prompt:
        "Summarize this for a second-grade student:\n\nJupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass one-thousandth that of the Sun, but two-and-a-half times that of all the other planets in the Solar System combined. Jupiter is one of the brightest objects visible to the naked eye in the night sky, and has been known to ancient civilizations since before recorded history. It is named after the Roman god Jupiter.[19] When viewed from Earth, Jupiter can be bright enough for its reflected light to cast visible shadows,[20] and is on average the third-brightest natural object in the night sky after the Moon and Venus.",
      temperature: 0.7,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "English to other languages",
    id: "English",
    desc: "Translates English text into French, Spanish and Japanese.",
    color: "#FEDA15",
    img: "https://icon-library.com/images/google-translate-icon/google-translate-icon-11.jpg",
    opt: {
      model: "text-davinci-003",
      prompt:
        "Translate this into 1. French, 2. Spanish and 3. Japanese:\n\nWhat rooms do you have available?\n\n1.",
      temperature: 0.3,
      max_tokens: 100,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Text to command",
    id: "Text",
    desc: "Translate text into programmatic commands.",
    color: "#FC4DB0",
    img: "https://static.thenounproject.com/png/1406093-200.png",
    opt: {
      model: "text-davinci-003",
      prompt:
        "Convert this text to a programmatic command:\n\nExample: Ask Constance if we need some bread\nOutput: send-msg `find constance` Do we need some bread?\n\nReach out to the ski store and figure out if I can get my skis fixed before I leave on Thursday",
      temperature: 0,
      max_tokens: 100,
      top_p: 1.0,
      frequency_penalty: 0.2,
      presence_penalty: 0.0,
      stop: ["\n"],
    },
  },
  {
    name: "Natural language to OpenAI API",
    id: "Natural",
    color: "#221530",
    img: "https://dwglogo.com/wp-content/uploads/2019/03/1600px-OpenAI_logo.png",
    desc: "Create code to call to the OpenAI API using a natural language instruction.",
    opt: {
      model: "text-davinci-003",
      prompt:
        '"""\nUtil exposes the following:\nutil.openai() -> authenticates & returns the openai module, which has the following functions:\nopenai.Completion.create(\n    prompt="<my prompt>", # The prompt to start completing from\n    max_tokens=123, # The max number of tokens to generate\n    temperature=1.0 # A measure of randomness\n    echo=True, # Whether to return the prompt in addition to the generated completion\n)\n"""\nimport util\n"""\nCreate an OpenAI completion starting from the prompt "Once upon an AI", no more than 5 tokens. Does not include the prompt.\n"""\n',
      temperature: 0,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
      stop: ['"""'],
    },
  },
];
